### ISSUE TITLE
Setup a "gitter".

### ISSUE THREAD

**Issue by howardroark** [GeppettoJS/backbone.geppetto#82]
I think this project could use a gitter account.  Saves you from having folks like me trying to have conversations in the github issues :P 

https://gitter.im/marionettejs/backbone.marionette

Marionette's has thousands of people in it helping each other out.  Sort of like IRC, but more accessible.  If you set one up it automatically sends a pull request to add a link to the README :)

**Comment by geekdave** [comment]
Sounds good to me!  Done in https://github.com/GeppettoJS/backbone.geppetto/pull/83
