### ISSUE TITLE
Missing from bower.

### ISSUE THREAD

**Issue by howardroark** [GeppettoJS/backbone.geppetto#84]
I think this repo may have gone missing from bower since it moved... http://bower.io/search/?q=geppetto

Any chance of adding it back?  

Thanks!

**Comment by geekdave** [comment]
Fixed in https://github.com/GeppettoJS/backbone.geppetto/pull/85

**Comment by howardroark** [comment]
Could you try to register it with bower again if you have a free moment?

**Comment by geekdave** [comment]
@howardroark: I re-registered it as `backbone-geppetto`.  The web-based search seems not to have been refreshed yet, but it's available via the command line:

```shell
$ bower install backbone-geppetto
bower backbone-geppetto#*   not-cached git://github.com/GeppettoJS/backbone.geppetto.git#*
bower backbone-geppetto#*      resolve git://github.com/GeppettoJS/backbone.geppetto.git#*
bower backbone-geppetto#*     download https://github.com/GeppettoJS/backbone.geppetto/archive/0.7.1.tar.gz
bower backbone-geppetto#*      extract archive.tar.gz
bower backbone-geppetto#*     resolved git://github.com/GeppettoJS/backbone.geppetto.git#0.7.1
bower underscore#~1.5.2     not-cached git://github.com/jashkenas/underscore.git#~1.5.2
bower underscore#~1.5.2        resolve git://github.com/jashkenas/underscore.git#~1.5.2
bower backbone#~1.1.0       not-cached git://github.com/jashkenas/backbone.git#~1.1.0
bower backbone#~1.1.0          resolve git://github.com/jashkenas/backbone.git#~1.1.0
bower underscore#~1.5.2       download https://github.com/jashkenas/underscore/archive/1.5.2.tar.gz
bower backbone#~1.1.0         download https://github.com/jashkenas/backbone/archive/1.1.2.tar.gz
bower underscore#~1.5.2        extract archive.tar.gz
bower underscore#~1.5.2   invalid-meta underscore is missing "main" entry in bower.json
bower underscore#~1.5.2   invalid-meta underscore is missing "ignore" entry in bower.json
bower underscore#~1.5.2       resolved git://github.com/jashkenas/underscore.git#1.5.2
bower backbone#~1.1.0          extract archive.tar.gz
bower backbone#~1.1.0         resolved git://github.com/jashkenas/backbone.git#1.1.2
bower backbone-geppetto#~0.7.1 install backbone-geppetto#0.7.1
bower underscore#~1.5.2        install underscore#1.5.2
bower backbone#~1.1.0          install backbone#1.1.2

backbone-geppetto#0.7.1 bower_components/backbone-geppetto
├── backbone#1.1.2
└── underscore#1.5.2

underscore#1.5.2 bower_components/underscore

backbone#1.1.2 bower_components/backbone
```

**Comment by howardroark** [comment]
Great!  Say... I'm not bower expert but does the `name` property in the JSON config need to line up with the registry?

https://github.com/GeppettoJS/backbone.geppetto/blob/master/bower.json#L2

**Comment by creynders** [comment]
@howardroark AFAICT the name isn't really used. If I `bower install backbone-geppetto` it's resolved and installed into a `bower_components/backbone-geppetto` directory.

What does bother me though is that it's registered on npm as `backbone.geppetto` and on bower as `backbone-geppetto`. That said, I started working on v0.8 this weekend and (so far) it looks like the hard dependency on backbone isn't really necessary, so maybe we should consider dropping "backbone" from the name altogether, @geekdave ? I'm opening a new issue to discuss v0.8
